config/routes.rb
Rails.application.routes.draw do

  get 'api/lectures/statistics'

  post 'api/comment_children' => "api/comment_children#create"

  get 'api/comment_children/edit' => "api/comment_children#edit"

  put 'api/comment_children' => "api/comment_children#update"

  delete 'api/comment_children' => "api/comment_children#destroy"

  put 'api/comments/:id/like' => "api/comments#like"

  get 'api/users/:id' => "api/users#index"

  get 'v/:id' => "api/lectures#v"
  get 'lecture/:id' => "api/lectures#v"
  get 'upload' => "api/lectures#v"
  get 'home' => "api/lectures#v"
  get 'user/login' => "api/users#v"

  apipie
  namespace :api do
    resource :users
    resource :comments
    resources :lectures
    resource :replay_ats
    resource :notifications
    resource :choices
    resource :answers
    resource :questions
  end
 #  resources :comments do
 #   member do
 #     put 'like' => "comments#like"
 #   end
 # end

  get '/logout' => "api/users#logout"
  get 'api/answers/question' => "api/answers#index"
  post 'api/notifications/check'
  put 'api/lectures/shortenurl/:id' => "api/lectures#shortenurl"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :questions

  validates :title, :url, presence: true
end

app/controllers/api/lectures_controller.rb
class Api::LecturesController < ApplicationController
  before_action :login_check, only: [:show, :edit, :create, :update, :destroy]
  before_action :set_lecture, only: [:show, :edit, :update, :destroy, :statistics]

  api :GET, '/lectures', '(특정 유저가 업로드한) 강의들 불러오기'
  param :page, :number, :desc => "강의 페이지"
  def index
    @lectures = Lecture.where(user_id: session[:user_id]).order(created_at: :desc).paginate(page: params[:page], per_page: 12)
    render json: @lectures
  end

  # GET /lectures
  # GET /lectures.json
  api :GET, '/lectures/:id', '특정 강의 불러오기'
  param :id, :number, :desc => "lecture ID"
  def show
    render json: @lecture
  end

  api :GET, '/lectures/:id/edit', '강의 수정 페이지'
  param :id, :number, :desc => "lecture ID"
  def edit
    if @lecture.user_id == session[:user_id]
      render json: @lecture, status: :ok
    else
      render json: {message: "게시물을 수정할 권한이 없습니다."}, status: :unauthorized
    end
  end

  api :POST, '/lectures', '강의 생성'
  param :title, String, :desc => "강의 제목"
  param :content, String, :desc => "강의 내용"
  param :subject, String, :desc => "강의 과목"
  param :textbook_range, String, :desc => "교재 범위"
  param :url, String, :desc => "강의 url 정보"
  param :thumbnail_url, String, :desc => "강의 thumbnail_url 정보"
  param :duration, :number, :desc => "강의 시간"
  def create
    @lecture = Lecture.new(lecture_params)

    if @lecture.save
      render json: @lecture, status: :ok
    else
      render json: {message: "강의 제목과 영상은 반드시 입력하셔야 합니다."}, status: :bad_request
    end
  end

  api :PUT, '/lectures/shortenurl/:id', 'shortenurl 저장'
  param :id, :number, :desc => "lecture ID"
  param :shorten_url, String, :desc => "강의 shorten_url"
  def shortenurl
    @lecture = Lecture.find(params[:id])
    @lecture.shorten_url = params[:shorten_url]
    if @lecture.save
      render json: @lecture, status: :ok
    else
      render json: {message: "shorten_url을 반드시 입력하셔야 합니다."}, status: :bad_request
    end
  end

  api :PUT, '/lectures/:id', '강의 업데이트'
  param :id, :number, :desc => "lecture ID"
  param :title, String, :desc => "강의 제목"
  param :content, String, :desc => "강의 설명"
  param :subject, String, :desc => "강의 과목"
  param :textbook_range, String, :desc => "교재 범위"
  param :url, String, :desc => "강의 url"
  param :thumbnail_url, String, :desc => "강의 thumbnail_url"
  param :duration, :number, :desc => "강의 시간"
  param :shorten_url, String, :desc => "강의 shorten_url"
  def update
    if @lecture.update(lecture_params)
      render json: @lecture, status: :ok
    else
      render json: {message: "강의 제목과 영상을 반드시 입력하셔야 합니다."}, status: :bad_request
    end
  end

  # DELETE /lectures
  # DELETE /lectures.json
  api :DELETE, '/lectures/:id', '강의 삭제'
  param :id, :number, :desc => "lecture ID"
  def destroy
    if @lecture.user_id == session[:user_id]
      @lecture.destroy
      head :ok
    else
      render json: {message: "게시물을 삭제할 권한이 없습니다."}, status: :unauthorized
    end
  end

  api :GET, '/lectures/statistics', '강의의 질문 및 학생 답'
  param :id, :number, :desc => "lecture ID"
  def statistics
    @ret = Hash.new

    @ret['questions'] = lectures = @lecture.questions.order(id: :asc)
    @ret['answers'] = Hash.new

    lectures.each do |question|
=begin
      if !@ret['answers'].key?(question.id)
        @ret['answers'][question.id] = Array.new
      end
=end
      @ret['answers'][question.id] = Answer.where(question_id: question.id)
    end

    render json: @ret
  end

  api :GET, '/v/:id', '(학생용) 특정 강의 링크(앞에 api 붙이지 X)'
  param :id, :number, :desc => "lecture ID"
  def v
    render file: 'public/index.html', layout: false
  end

  api :GET, '/lecture/:id', '(게시자용) 특정 강의 링크(앞에 api 붙이지 X)'
  param :id, :number, :desc => "lecture ID"
  api :GET, '/upload', '앞에 api 붙이지 X'
  api :GET, '/home', '앞에 api 붙이지 X'

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params[:user_id] = session[:user_id]
      params.permit(:user_id, :title, :content, :url, :thumbnail_url, :duration, :subject, :textbook_range, :shorten_url)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :lecture_user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :lecture_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :lecture_content %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :lecture_url %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_url %>
    <%= form.text_field :thumbnail_url, id: :lecture_thumbnail_url %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration, id: :lecture_duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Url</th>
      <th>Thumbnail url</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.user_id %></td>
        <td><%= lecture.title %></td>
        <td><%= lecture.content %></td>
        <td><%= lecture.url %></td>
        <td><%= lecture.thumbnail_url %></td>
        <td><%= lecture.duration %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @lecture.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @lecture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @lecture.content %>
</p>

<p>
  <strong>Url:</strong>
  <%= @lecture.url %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @lecture.thumbnail_url %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lecture.duration %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>