config/routes.rb
Rails.application.routes.draw do

  get 'api/lectures/statistics'

  post 'api/comment_children' => "api/comment_children#create"

  get 'api/comment_children/edit' => "api/comment_children#edit"

  put 'api/comment_children' => "api/comment_children#update"

  delete 'api/comment_children' => "api/comment_children#destroy"

  put 'api/comments/:id/like' => "api/comments#like"

  get 'api/users/:id' => "api/users#index"

  get 'v/:id' => "api/lectures#v"
  get 'lecture/:id' => "api/lectures#v"
  get 'upload' => "api/lectures#v"
  get 'home' => "api/lectures#v"
  get 'user/login' => "api/users#v"

  apipie
  namespace :api do
    resource :users
    resource :comments
    resources :lectures
    resource :replay_ats
    resource :notifications
    resource :choices
    resource :answers
    resource :questions
  end
 #  resources :comments do
 #   member do
 #     put 'like' => "comments#like"
 #   end
 # end

  get '/logout' => "api/users#logout"
  get 'api/answers/question' => "api/answers#index"
  post 'api/notifications/check'
  put 'api/lectures/shortenurl/:id' => "api/lectures#shortenurl"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lecture
  has_many :comment_children, dependent: :destroy
  acts_as_votable
end

app/models/comment_child.rb
class CommentChild < ApplicationRecord
	belongs_to :comment
  belongs_to :user
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :questions

  validates :title, :url, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  validates :notification_type, :content, :url, presence: true

  def self.new_notification(user_id, lecture_id, from)
  	target = Lecture.find(lecture_id).user_id
  	notification_type = 1
  	url = '{"lecture_id":' + lecture_id.to_s + '}'

  	if from == 'comment'
  		content = User.find(user_id).username + '님이 강의에 질문을 달았습니다.'
  	else
  		content = ''
  	end

  	Notification.create(user_id: target, notification_type: notification_type, content: content, url: url)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lecture
  has_many :choices, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :content, :correct_answer, presence: true
end

app/models/replay_at.rb
class ReplayAt < ApplicationRecord
  belongs_to :user
  belongs_to :lecture

  validates :playtime, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lectures
  has_many :answers
  has_many :comments
  has_many :comment_children
  has_many :replay_ats, dependent: :destroy
  has_many :notifications, dependent: :destroy
  acts_as_voter

  validates_presence_of :username, :email
  validates :email, uniqueness: true

end

app/controllers/api/notifications_controller.rb
class Api::NotificationsController < ApplicationController
  before_action :login_check
  before_action :set_notification, only: [:update, :destroy]

  api :GET, '/notifications', '유저 알림'
  def show
    @notifications = Notification.where(user_id: session[:user_id]).order(created_at: :desc).limit(20)
    render json: @notifications
  end

  api :POST, '/notifications', '유저 알림 생성'
  param :user_id, :number, :desc => "알림을 보낼 유저 ID"
  param :notification_type, :number, :desc => "알림 타입"
  param :content, String, :desc => "알림 내용"
  param :url, String, :desc => "알림 url 정보"
  def create
    @notification = Notification.new(notification_params)

    if @notification.save
      render json: @notification, status: :ok
    else
      render json: {message: "유저 ID, 알림 내용 등을 입력해주세요."}, status: :bad_request
    end
  end

  api :PUT, '/notifications', '유저 알림 업데이트'
  param :id, :number, :desc => "notification ID"
  param :notification_type, :number, :desc => "알림 타입"
  param :content, String, :desc => "알림 내용"
  param :url, String, :desc => "알림 url 정보"
  def update
    if @notification.update(notification_params)
      render json: @notification, status: :ok
    else
      render json: {message: "유저 ID, 알림 내용 등을 입력해주세요."}, status: :bad_request
    end
  end

  api :DELETE, '/notifications', '유저 알림 삭제'
  param :id, :number, :desc => "notification ID"
  def destroy
    if @notification.user_id == session[:user_id]
      @notification.destroy
      head :ok
    else
      render json: {message: "알람을 삭제할 권한이 없습니다."}, status: :unauthorized
    end
  end

  api :POST, '/notifications/check'
  def check
    if Notification.where(user_id: session[:user_id]).update_all(notification_type: 0)
      head :ok
    else
      render json: {message: "알람 상태를 업데이트 하지 못 했습니다."}, status: :bad_request
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params['id'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.permit(:user_id, :notification_type, :content, :url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::RequestForgeryProtection
  #protect_from_forgery unless: -> { request.format.json? }
  #rescue_from Exception, with: :render_500
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from ActionController::UnknownController, with: :render_404
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_500
    render json: {message: "서버 내부에 오류가 발생했습니다."}, status: :internal_server_error
  end

  def render_404
    render json: {message: "페이지가 존재하지 않습니다."}, status: :not_found
  end

  def login_check
    if session[:user_id].nil?
      @error = {message: "로그인이 필요합니다."}
      render json: @error, status: :unauthorized
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_path(file, directory)
    return AssetLoader.get_asset_path(file, directory)
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/comment_children_helper.rb
module CommentChildrenHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replay_ats_helper.rb
module ReplayAtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :notification_user_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :notification_type %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :notification_content %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :notification_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Content</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user_id %></td>
        <td><%= notification.type %></td>
        <td><%= notification.content %></td>
        <td><%= notification.url %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @notification.type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Url:</strong>
  <%= @notification.url %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>