config/routes.rb
Rails.application.routes.draw do

  get 'api/lectures/statistics'

  post 'api/comment_children' => "api/comment_children#create"

  get 'api/comment_children/edit' => "api/comment_children#edit"

  put 'api/comment_children' => "api/comment_children#update"

  delete 'api/comment_children' => "api/comment_children#destroy"

  put 'api/comments/:id/like' => "api/comments#like"

  get 'api/users/:id' => "api/users#index"

  get 'v/:id' => "api/lectures#v"
  get 'lecture/:id' => "api/lectures#v"
  get 'upload' => "api/lectures#v"
  get 'home' => "api/lectures#v"
  get 'user/login' => "api/users#v"

  apipie
  namespace :api do
    resource :users
    resource :comments
    resources :lectures
    resource :replay_ats
    resource :notifications
    resource :choices
    resource :answers
    resource :questions
  end
 #  resources :comments do
 #   member do
 #     put 'like' => "comments#like"
 #   end
 # end

  get '/logout' => "api/users#logout"
  get 'api/answers/question' => "api/answers#index"
  post 'api/notifications/check'
  put 'api/lectures/shortenurl/:id' => "api/lectures#shortenurl"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :lecture
  has_many :comment_children, dependent: :destroy
  acts_as_votable
end

app/models/comment_child.rb
class CommentChild < ApplicationRecord
	belongs_to :comment
  belongs_to :user
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :questions

  validates :title, :url, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  validates :notification_type, :content, :url, presence: true

  def self.new_notification(user_id, lecture_id, from)
  	target = Lecture.find(lecture_id).user_id
  	notification_type = 1
  	url = '{"lecture_id":' + lecture_id.to_s + '}'

  	if from == 'comment'
  		content = User.find(user_id).username + '님이 강의에 질문을 달았습니다.'
  	else
  		content = ''
  	end

  	Notification.create(user_id: target, notification_type: notification_type, content: content, url: url)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lecture
  has_many :choices, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :content, :correct_answer, presence: true
end

app/models/replay_at.rb
class ReplayAt < ApplicationRecord
  belongs_to :user
  belongs_to :lecture

  validates :playtime, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lectures
  has_many :answers
  has_many :comments
  has_many :comment_children
  has_many :replay_ats, dependent: :destroy
  has_many :notifications, dependent: :destroy
  acts_as_voter

  validates_presence_of :username, :email
  validates :email, uniqueness: true

end

app/controllers/api/answers_controller.rb
class Api::AnswersController < ApplicationController
  before_action :login_check, only: [:index, :show, :create, :destroy]
  before_action :set_answer, only: :destroy

  api :GET, '/answers/question', '특정 question에 대한 학생들의 답'
  param :question_id, :number, :desc => "질문 ID", :required => true
  def index
    @answers = Answer.where(question_id: params[:question_id])
    render json: @answers
  end


  api :GET, '/answers', '특정 학생의 특정 강의에 대한 답 리스트'
  param :lecture_id, :number, :desc => "강의 ID", :required => true
  def show
    @answers = Answer.where(user_id: 22)
    @answers2 = Hash.new
    @answers.each do |answer|
      if answer.question.lecture_id == params[:lecture_id].to_i
        unless @answers2.key?(answer.question_id)
          @answers2[answer.question_id] = Array.new
        end
        @answers2[answer.question_id] << answer
      end
    end
    render json: @answers2
  end

  api :POST, '/answers', '특정 question에 대한 학생의 답 생성'
  param :question_id, :number, :desc => "질문 ID", :required => true
  param :answer, String, :desc => "학생 답", :required => true
  def create
    @answer = Answer.new(answer_params)


      if @answer.save
        render json: @answer, status: :ok
      else
        render json: {message: "답은 반드시 입력해야 합니다."}, status: :bad_request
      end
  end


  # DELETE /answers/1
  # DELETE /answers/1.json
  api :DELETE, '/answers', '특정 question에 대한 학생 답 삭제'
  param :id, :number, :desc => "학생 답 ID", :required => true
  def destroy
    @answer.destroy
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params[:user_id] = session[:user_id]
      params.permit(:user_id, :question_id, :answer)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::RequestForgeryProtection
  #protect_from_forgery unless: -> { request.format.json? }
  #rescue_from Exception, with: :render_500
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from ActionController::UnknownController, with: :render_404
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_500
    render json: {message: "서버 내부에 오류가 발생했습니다."}, status: :internal_server_error
  end

  def render_404
    render json: {message: "페이지가 존재하지 않습니다."}, status: :not_found
  end

  def login_check
    if session[:user_id].nil?
      @error = {message: "로그인이 필요합니다."}
      render json: @error, status: :unauthorized
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_path(file, directory)
    return AssetLoader.get_asset_path(file, directory)
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/comment_children_helper.rb
module CommentChildrenHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replay_ats_helper.rb
module ReplayAtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :answer_user_id %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id, id: :answer_question_id %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :answer_answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>